# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_name', models.CharField(max_length=25)),
                ('result_types', models.CharField(max_length=100)),
            ],
        ),
    ]
