# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0002_resulttypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultTypes',
            new_name='ResultType',
        ),
        migrations.RenameModel(
            old_name='SatelliteBands',
            new_name='SatelliteBand',
        ),
    ]
