# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0003_auto_20160620_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=25)),
                ('satellite_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='resulttype',
            name='result_types',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='satelliteband',
            name='available_bands',
            field=models.CharField(max_length=25),
        ),
    ]
