# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0004_auto_20160620_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resulttype',
            old_name='result_types',
            new_name='result_type',
        ),
        migrations.RenameField(
            model_name='resulttype',
            old_name='satellite_name',
            new_name='satellite_id',
        ),
        migrations.RenameField(
            model_name='satelliteband',
            old_name='platform',
            new_name='band_name',
        ),
        migrations.RenameField(
            model_name='satelliteband',
            old_name='satellite_name',
            new_name='satellite_id',
        ),
        migrations.RemoveField(
            model_name='satelliteband',
            name='available_bands',
        ),
        migrations.AddField(
            model_name='satelliteband',
            name='band_number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
