# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0008_auto_20160622_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='time_end',
            field=models.DateField(verbose_name='time_end'),
        ),
        migrations.AlterField(
            model_name='query',
            name='time_start',
            field=models.DateField(verbose_name='time_start'),
        ),
    ]
