# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0010_auto_20160623_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='scene_list',
            field=models.CharField(default='asdf', max_length=1000),
            preserve_default=False,
        ),
    ]
