# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0012_auto_20160629_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='latitude_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='latitude_min',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='longitude_max',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadata',
            name='longitude_min',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='latitude_max',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='latitude_min',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='longitude_max',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='longitude_min',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
