# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0021_auto_20160720_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='query_id',
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_path',
            field=models.CharField(max_length=251),
        ),
    ]
