# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0023_auto_20160720_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
