# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0025_result_percent_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='percent_complete',
        ),
        migrations.AddField(
            model_name='result',
            name='scenes_processed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='total_scenes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
