# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0026_auto_20160720_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='latitude_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='latitude_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='longitude_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='longitude_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='pixel_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='scene_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='query',
            name='latitude_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='query',
            name='latitude_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='query',
            name='longitude_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='query',
            name='longitude_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='latitude_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='latitude_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='longitude_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='longitude_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='scenes_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_scenes',
            field=models.IntegerField(default=0),
        ),
    ]
