# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0028_metadata_clean_pixel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='percentage_clean_pixels',
            field=models.FloatField(default=0),
        ),
    ]
