# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0030_auto_20160727_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='result_filled_path',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='resulttype',
            name='fill',
            field=models.CharField(default='red', max_length=25),
        ),
        migrations.AlterField(
            model_name='result',
            name='data_path',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_path',
            field=models.CharField(default='', max_length=250),
        ),
    ]
