# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0031_auto_20160727_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='scene_list',
            new_name='acquisition_list',
        ),
        migrations.AddField(
            model_name='metadata',
            name='clean_pixels_per_acquisition',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
