# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0032_auto_20160728_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='clean_pixel_percentages_per_acquisition',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='acquisition_list',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='clean_pixels_per_acquisition',
            field=models.CharField(max_length=100000),
        ),
    ]
