# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0033_auto_20160729_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(default='', max_length=250)),
                ('area_name', models.CharField(default='', max_length=250)),
                ('latitude_max', models.FloatField(default=0)),
                ('latitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('main_imagery', models.CharField(default='', max_length=250)),
                ('detail_imagery', models.CharField(default='', max_length=250)),
                ('detail_latitude_max', models.FloatField(default=0)),
                ('detail_latitude_min', models.FloatField(default=0)),
                ('detail_longitude_max', models.FloatField(default=0)),
                ('detail_longitude_min', models.FloatField(default=0)),
            ],
        ),
    ]
