# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0034_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='area_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
