# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0035_query_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_product',
            field=models.CharField(default='', max_length=250),
        ),
    ]
