# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0036_area_area_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='acquisition_list',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='clean_pixel_percentages_per_acquisition',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='clean_pixels_per_acquisition',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='query_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='query',
            name='area_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='measurements',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='platform',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='query',
            name='product',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='query',
            name='product_type',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_type',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='query',
            name='user_id',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='result',
            name='query_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
