# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0037_auto_20160906_1521'),
        ('custom_mosaic_tool', '0038_auto_20160819_1505'),
    ]

    operations = [
    ]
