# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mosaic_tool', '0039_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='product_type',
        ),
    ]
