# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(default='', max_length=250)),
                ('area_name', models.CharField(default='', max_length=250)),
                ('area_product', models.CharField(default='', max_length=250)),
                ('latitude_min', models.FloatField(default=0)),
                ('latitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('main_imagery', models.CharField(default='', max_length=250)),
                ('detail_imagery', models.CharField(default='', max_length=250)),
                ('detail_latitude_min', models.FloatField(default=0)),
                ('detail_latitude_max', models.FloatField(default=0)),
                ('detail_longitude_min', models.FloatField(default=0)),
                ('detail_longitude_max', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(default='', max_length=1000)),
                ('latitude_max', models.FloatField(default=0)),
                ('latitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('scene_count', models.IntegerField(default=0)),
                ('pixel_count', models.IntegerField(default=0)),
                ('clean_pixel_count', models.IntegerField(default=0)),
                ('percentage_clean_pixels', models.FloatField(default=0)),
                ('acquisition_list', models.CharField(default='', max_length=100000)),
                ('clean_pixels_per_acquisition', models.CharField(default='', max_length=100000)),
                ('clean_pixel_percentages_per_acquisition', models.CharField(default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.CharField(default='', max_length=1000)),
                ('area_id', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=10000)),
                ('user_id', models.CharField(default='', max_length=25)),
                ('query_start', models.DateTimeField(verbose_name='query_start')),
                ('query_end', models.DateTimeField(verbose_name='query_end')),
                ('query_type', models.CharField(default='', max_length=25)),
                ('platform', models.CharField(default='', max_length=25)),
                ('product', models.CharField(default='', max_length=25)),
                ('product_type', models.CharField(default='', max_length=25)),
                ('measurements', models.CharField(default='', max_length=100)),
                ('time_start', models.DateTimeField(verbose_name='time_start')),
                ('time_end', models.DateTimeField(verbose_name='time_end')),
                ('latitude_min', models.FloatField(default=0)),
                ('latitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(default='', max_length=100)),
                ('scenes_processed', models.IntegerField(default=0)),
                ('total_scenes', models.IntegerField(default=0)),
                ('latitude_max', models.FloatField(default=0)),
                ('latitude_min', models.FloatField(default=0)),
                ('longitude_max', models.FloatField(default=0)),
                ('longitude_min', models.FloatField(default=0)),
                ('result_path', models.CharField(default='', max_length=250)),
                ('result_filled_path', models.CharField(default='', max_length=250)),
                ('data_path', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=25)),
                ('result_id', models.CharField(max_length=25)),
                ('result_type', models.CharField(max_length=25)),
                ('red', models.CharField(max_length=25)),
                ('green', models.CharField(max_length=25)),
                ('blue', models.CharField(max_length=25)),
                ('fill', models.CharField(default='red', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=25)),
                ('satellite_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=25)),
                ('band_number', models.IntegerField()),
                ('band_name', models.CharField(max_length=25)),
            ],
        ),
    ]
