# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=25)),
                ('result_id', models.CharField(max_length=25)),
                ('product_type', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='ResultType',
        ),
        migrations.DeleteModel(
            name='SatelliteBand',
        ),
    ]
