# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_detection', '0002_auto_20160906_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutputProduct',
            new_name='ResultType',
        ),
    ]
