# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_detection', '0003_auto_20160906_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='result_filled_path',
            new_name='clear_observations_path',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='result_path',
            new_name='data_netcdf_path',
        ),
        migrations.AddField(
            model_name='result',
            name='water_observations_path',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='result',
            name='water_percentage_path',
            field=models.CharField(default='', max_length=250),
        ),
    ]
