# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_detection', '0005_auto_20160907_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='clean_pixel_count',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='percentage_clean_pixels',
        ),
        migrations.RemoveField(
            model_name='query',
            name='measurements',
        ),
        migrations.RemoveField(
            model_name='query',
            name='product_type',
        ),
    ]
