# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_detection', '0006_auto_20160907_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttype',
            name='fill',
            field=models.CharField(default='black', max_length=25),
            preserve_default=False,
        ),
    ]
