# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_detection', '0007_resulttype_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='clear_observations_path_filled',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='result',
            name='water_observations_path_filled',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='result',
            name='water_percentage_path_filled',
            field=models.CharField(default='', max_length=250),
        ),
    ]
