# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_detection', '0008_auto_20160907_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='clear_observations_path_filled',
            new_name='clear_observations_filled_path',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='water_observations_path_filled',
            new_name='water_observations_filled_path',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='water_percentage_path_filled',
            new_name='water_percentage_filled_path',
        ),
    ]
